'use client';
import { useEffect, useState, useSyncExternalStore } from 'react';
import Image from 'next/image';
import { publicAsset } from '@/lib/public-asset';
import { ArrowUpRight, ArrowDown, Plus, Minus, Sparkles, MessageCircle, MoveUpRight, Pause, Play, Menu, X, Download } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogClose } from '@/components/ui/dialog';

const motionQuery = '(prefers-reduced-motion: reduce)';
const subscribeMotion = (callback: () => void) => { const media = window.matchMedia(motionQuery); media.addEventListener('change', callback); return () => media.removeEventListener('change', callback); };
const readMotion = () => !window.matchMedia(motionQuery).matches;
const serverMotion = () => false;
export default function Home() {
  const [contact, setContact] = useState(false);
  const [menu, setMenu] = useState(false);
  const [motionOverride, setMotion] = useState<boolean | null>(null);
  const preferredMotion = useSyncExternalStore(subscribeMotion, readMotion, serverMotion);
  const motion = motionOverride ?? preferredMotion;
  return <>
    <a href="#about" className="skip-link">跳到正文</a>
    <header className="site-header">
      <a className="brand" href="#home" aria-label="星哥首页"><span className="brand-mark">✳</span><strong>星哥<span className="brand-en">XING GE</span></strong></a>
      <nav className={menu ? 'navigation is-open' : 'navigation'} aria-label="主导航"><a href="#about" onClick={() => setMenu(false)}>关于我</a><a href="#projects" onClick={() => setMenu(false)}>参与项目</a><a href="#connect" onClick={() => setMenu(false)}>合作方向</a></nav>
      <div className="header-actions"><button className="nav-contact" onClick={() => setContact(true)}>聊聊合作 <ArrowUpRight size={17}/></button><button className="menu-toggle" aria-label={menu ? '关闭导航' : '打开导航'} aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? <X/> : <Menu/>}</button></div>
    </header>
    <main>
      <section className="hero" id="home">
        <div className="hero-cross cross-one" aria-hidden="true">+</div>
        <div className="hero-copy"><p className="eyebrow"><span className="live-dot"/> OPEN TO POSSIBILITIES <span className="eyebrow-line"/></p><p className="hero-intro">我是星哥，一个持续探索的实干派。</p><h1>让想法，<br/>成为<span className="accent-word">现实<span className="title-spark" aria-hidden="true">✳</span></span>。</h1><p className="hero-description">聊生意、聊 AI，也聊你下一步怎么走。<br/>把经验、技术和资源连接起来，<br className="mobile-break"/>一起做点有价值的事。</p><div className="hero-actions"><button className="button-primary" onClick={() => setContact(true)}>认识一下，聊聊机会 <ArrowUpRight size={20}/></button><a className="text-link" href="#projects">探索我的项目 <ArrowDown size={16}/></a></div><div className="hero-signature"><span className="signature-line"/><span>保持好奇，认真做事。</span><span className="small-star">✦</span></div></div>
        <div className="hero-visual"><div className="orb-fallback"/><div className="portrait-window"><Image unoptimized src={publicAsset('/images/xingge.jpg')} width="1080" height="1080" alt="星哥喜欢的黑发动漫人物头像" fetchPriority="high"/></div><div className="orb-slot" id="orbit-mount"/><div className="orb-coordinate">XG — 001<br/><span>IDEAS INTO REALITY</span></div><div className="portrait-caption"><span className="live-dot"/> 星哥 / 九星 <span>EXPLORER · BUILDER</span></div><span className="orbit-label label-top">思考 / THINK</span><span className="orbit-label label-bottom">创造 / BUILD</span></div>
        <div className="hero-bottom"><a href="#about"><ArrowDown size={16}/> 向下探索</a><span>AI × BUSINESS × CONNECTION</span><button aria-label={motion ? '暂停动态效果' : '开启动态效果'} onClick={() => setMotion(!motion)}>{motion ? <Pause size={14}/> : <Play size={14}/>} {motion ? '动态开启' : '动态暂停'}</button></div>
      </section>
      <div className="manifesto-strip" aria-hidden="true"><span>STAY CURIOUS</span><i>✳</i><span>BUILD SOMETHING REAL</span><i>✳</i><span>保持好奇 · 认真做事</span><i>✳</i></div>
      <section className="section about" id="about"><div className="section-label"><span>01 / ABOUT ME</span><span>始终在场，持续探索</span></div><div className="about-layout"><div className="about-heading"><p className="overline">生意在变，好奇心不变。</p><h2>做过不同的项目，<br/>更在意<span className="muted-heading">事情怎么做成。</span></h2><div className="profile-mini"><Image unoptimized src={publicAsset('/images/xingge.jpg')} width="48" height="48" alt="星哥动漫头像" loading="lazy"/><div><strong>星哥 / 九星</strong><span>项目参与者 · AI 探索者</span></div><span className="profile-star">✳</span></div></div><div className="about-copy"><p>这些年，我做过不少项目，也接触过不同的生意。从数字服务到 AI 应用，我一直在寻找技术与真实需求的交点。</p><p>我关心一个想法解决谁的问题，怎样找到客户，以及能否用合理的成本开始验证。把这些聊清楚，下一步才有方向。</p><p className="about-emphasis">机会很多。适合你的，才值得认真做。</p><a className="underlined-link" href="https://www.zhihu.com/search?type=content&q=%E4%B9%9D%E6%98%9F" target="_blank" rel="noopener noreferrer">想了解更多？知乎搜索「九星」 <ArrowUpRight size={17}/></a></div></div></section>
      <section className="section projects" id="projects"><div className="section-label"><span>02 / SELECTED PROJECTS</span><span>真实参与 · 持续实践</span></div><div className="section-heading"><h2>想法，<span className="muted-heading">已有回响。</span></h2><p>三个真实参与的项目，三个不同的探索方向。<br/>从数字服务，到内容创作，再到日常陪伴。</p></div><div className="project-grid">
        <article className="project-card"><div className="project-visual commerce-visual"><span className="visual-index">01 / DIGITAL COMMERCE</span><div className="store-preview" aria-label="数字服务商店概念界面"><div className="mock-top"><span className="mock-logo">V.</span><span>数字服务 / DIGITAL STORE</span><span className="mock-dot"/></div><div className="mock-store-title">工具就位。<br/><span>想法，开始运行。</span></div><div className="store-items"><div><Sparkles/><span>AI 工具</span></div><div><span className="product-glyph">↗</span><span>数字订阅</span></div><div><span className="product-glyph">⌘</span><span>效率应用</span></div></div><div className="mock-store-footer"><span>探索数字服务</span><ArrowUpRight size={17}/></div></div><span className="concept-label">概念界面</span></div><div className="project-body"><div className="project-meta"><span>数字服务</span><span className="project-status"><i/> 公开项目</span></div><h3>Venom-AI <ArrowUpRight size={22}/></h3><p>围绕 AI 工具与数字订阅的服务商店，连接商品浏览、订单查询与服务支持。</p><div className="project-tags"><span>数字商品</span><span>订阅服务</span><span>在线商店</span></div><a className="project-link" href="https://duye66.com/" target="_blank" rel="noopener noreferrer">访问项目 <ArrowUpRight size={16}/></a></div></article>
        <article className="project-card"><div className="project-visual writing-visual"><span className="visual-index">02 / AI CONTENT</span><div className="writing-preview" aria-label="AI 内容工作台概念界面"><div className="mock-top"><span className="mock-logo">✳</span><span>CONTENT / WORKSPACE</span></div><div className="writing-heading">从一个想法，<br/>到一篇好内容。</div><div className="writing-input"><span>输入你的灵感…</span><span>↗</span></div><div className="writing-steps"><span>发现选题</span><span>辅助创作</span><span>内容复盘</span></div><div className="text-lines"><i/><i/><i/></div></div><span className="concept-label">匿名概念界面</span></div><div className="project-body"><div className="project-meta"><span>AI 内容应用</span><span className="project-status private"><i/> 持续开发</span></div><h3>内容创作工作台 <span className="project-number">02</span></h3><p>围绕选题发现、辅助写作与内容复盘，探索 AI 在创作工作流里的实际价值。</p><div className="project-tags"><span>选题研究</span><span>辅助写作</span><span>工作流</span></div><button className="project-link" onClick={() => setContact(true)}>交流这个方向 <ArrowUpRight size={16}/></button></div></article>
        <article className="project-card"><div className="project-visual companion-visual"><span className="visual-index">03 / PERSONAL AI</span><div className="companion-preview" aria-label="个人 AI 助手概念界面"><div className="companion-orbit"><span>✦</span></div><div className="chat-bubble bubble-one">把今天的想法记下来。</div><div className="chat-bubble bubble-two"><span className="chat-star">✳</span> 好，我们一步步梳理。<div className="chat-line"/></div><div className="companion-detail"><span>记忆</span><i/><span>对话</span><i/><span>日常陪伴</span></div></div><span className="concept-label">匿名概念界面</span></div><div className="project-body"><div className="project-meta"><span>AI 智能体</span><span className="project-status private"><i/> 持续开发</span></div><h3>有记忆的 AI 伙伴 <span className="project-number">03</span></h3><p>以持续对话、长期记忆和日常辅助为方向，探索更贴近个人生活的 AI 体验。</p><div className="project-tags"><span>长期记忆</span><span>个性化</span><span>智能体</span></div><button className="project-link" onClick={() => setContact(true)}>交流这个方向 <ArrowUpRight size={16}/></button></div></article>
      </div><p className="projects-note">部分项目仍在开发维护中，以匿名概念界面呈现方向；具体参与经历与合作细节，欢迎私下交流。</p></section>
      <section className="section connection" id="connect"><div className="section-label"><span>03 / LET’S CONNECT</span><span>连接起来，才有新的可能</span></div><div className="connect-grid"><div><p className="overline">你的下一步，可以从这里开始。</p><h2>把你的资源，<br/>接入<span className="accent-word">新的可能。</span></h2><p className="connect-intro">带着你的实际情况来。我们从具体的问题出发，<br/>看看哪些方向值得一起推进。</p><div className="cooperation-list">{[{n:'01',title:'你有想法，想找到落地路径',body:'聊清楚需求、能力与投入，先找到一个可以验证的起点。'},{n:'02',title:'你有业务，想探索 AI 应用',body:'从内容、服务和效率里的具体问题切入，讨论合适的应用方式。'},{n:'03',title:'你有项目或资源，想找合作',body:'把产品、渠道与各自能做的事情讲清楚，寻找互相适合的合作点。'}].map(item=><details key={item.n}><summary><span>{item.n}</span><strong>{item.title}</strong><Plus className="details-plus" size={18}/><Minus className="details-minus" size={18}/></summary><p>{item.body}</p></details>)}</div></div><div className="network-panel"><div className="network-label"><span className="live-dot"/> CONNECTION MAP<span>连接 · 共创</span></div><div id="network-mount" className="network-mount"><div className="network-fallback">想法 · 技术 · 产品 · 内容 · 渠道 · 合作</div></div><p className="network-hint" id="network-description">选择一个节点，看看我们可以聊什么。</p></div></div></section>
      <section className="contact-section" id="contact"><div id="flow-mount" className="flow-mount" aria-hidden="true"/><div className="contact-content"><p className="eyebrow"><span className="live-dot"/> YOUR NEXT MOVE</p><h2>下一次可能，<br/>从一句<span className="accent-word">「你好」</span>开始。</h2><p>我是星哥。很高兴，在这里认识你。</p><button className="button-primary large" onClick={() => setContact(true)}>添加微信，聊聊你的想法 <MoveUpRight size={24}/></button><span className="contact-note">添加时请备注：你的行业 + 想聊的事情</span></div><span className="contact-background-type" aria-hidden="true">LET’S TALK</span></section>
    </main>
    <footer><a className="brand" href="#home"><span className="brand-mark">✳</span><strong>星哥<span className="brand-en">XING GE</span></strong></a><span>保持好奇，认真做事。</span><a href="#home">回到顶部 <ArrowUpRight size={16}/></a></footer>
    <button className="floating-contact" onClick={() => setContact(true)} aria-label="添加星哥微信"><MessageCircle size={21}/><span>聊聊合作</span></button>
    <Dialog open={contact} onOpenChange={setContact}><DialogContent className="contact-dialog" showCloseButton={false}><DialogClose className="dialog-close" aria-label="关闭微信二维码"><X size={21}/></DialogClose><div className="dialog-kicker"><span className="live-dot"/> NICE TO MEET YOU</div><DialogTitle className="dialog-title">你好，我是星哥。</DialogTitle><DialogDescription className="dialog-description">微信扫一扫，或保存二维码后在微信中识别。<br/>添加时请备注：你的行业 + 想聊的事情。</DialogDescription><Image unoptimized className="wechat-qr" src={publicAsset('/images/wechat.jpg')} width="888" height="1131" alt="九星的微信好友二维码"/><a className="button-primary qr-download" href={publicAsset('/images/wechat.jpg')} download="星哥微信二维码.jpg">保存微信二维码 <Download size={18}/></a><p className="qr-tip">手机端也可长按二维码保存到相册。</p></DialogContent></Dialog>
    <VisualEffects enabled={motion}/>
  </>;
}
function VisualEffects({enabled}:{enabled:boolean}) {
  useEffect(() => {
    let disposed = false; let cleanup: (() => void) | undefined;
    import('@/lib/visuals').then(({mountVisuals}) => { if (disposed) return; const release = mountVisuals(enabled); if (disposed) release(); else cleanup = release; }).catch(() => { /* Core content remains usable if graphics cannot load. */ });
    return () => { disposed = true; cleanup?.(); };
  }, [enabled]);
  return null;
}



